// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace DBConnect
{
    public partial class DemoHotelContext : DbContext
    {
        public DemoHotelContext()
        {
        }

        public DemoHotelContext(DbContextOptions<DemoHotelContext> options)
            : base(options)
        {
        }

        public virtual DbSet<DemoFacility> DemoFacility { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<DemoFacility>(entity =>
            {
                entity.HasKey(e => e.Facility_No)
                    .HasName("PK__DemoFaci__CEAA7B4AD100EE89");

                entity.Property(e => e.Facility_No)
                    .ValueGeneratedNever()
                    .HasColumnName("Facility_No");

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(30)
                    .IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}