// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBConnect
{
    public partial class DemoFacility
    {
        public int Facility_No { get; set; }
        public string Name { get; set; }
    }
}